### ISSUE TITLE
'buffer' attribute parameter is out of bounds: must be between 0 and 30

### ISSUE THREAD

**Issue by vili-1** [mc-imperial/spirv-control-flow#17]
For three fleshed examples coming from the Vulkan CTS (see [here](https://imperiallondon-my.sharepoint.com/:u:/g/personal/jclark2_ic_ac_uk/EcnJ5yBEjD9Kvqvw2hNLZuABP_e-W8kmIv3MqYO35iFHDg?e=L2lViL)), the following error is returned:

```
xcrun -sdk macosx metal -c s207_test_0_4286858354608860846.metal -o s207_test_0_4286858354608860846.air
s207_test_0_4286858354608860846.metal:26:994: error: 
      'buffer' attribute parameter is out of bounds: must be between 0 and 30
  ..._19 [[buffer(29)]], device _6& _10 [[buffer(30)]], device _8& _41 [[buffer(31)]])
                                                                                ^
1 error generated.
```

These are the three `.metal` files returning the compilation error in question:
```
s207_test_0_4286858354608860846.metal
s207_test_0_4668013226902027755.metal
s207_test_0_776553494991665668.metal
```
Attached one of them:
[Archive.zip](https://github.com/mc-imperial/spirv-control-flow/files/8642596/Archive.zip)

**Comment by afd** [comment]
Interesting - my guess is that Metal must place a limit on the number of buffers that it is legal to declare and we are exceeding that limit.

I suggest we ignore this particular error message.

@Jack-Clark for info.
